//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCRemoteValidation.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class MVCRemoteValidationtbl
    {
        public int Id { get; set; }
        [Remote("IsValidName", "User",ErrorMessage="Enter alternate name")]
        public string UserName { get; set; }
        public string Password { get; set; }
    }

     
}
